global using managementcheck.Data;
global using managementcheck.Enums;
global using managementcheck.Interfaces;
global using managementcheck.Models;
global using managementcheck.ViewModels;
global using Dapper;
global using Microsoft.EntityFrameworkCore;
global using Npgsql;
global using System.ComponentModel.DataAnnotations;